services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: gopod-s
    expose:
      - 8080
    environment:
      - JWT_SECRET_KEY=u19kaneh90skwit4bskhagwl2
      - CLIENT_URL=http://client:5173
    restart: always
    networks:
      - gopod-net
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=http://server:8080
        - BACKEND_WS_URL=ws://server:8080/ws
    image: gopod-c
    ports:
      - 5173:5173
    depends_on:
      - server
    restart: always
    networks:
      - gopod-net
networks:
  gopod-net:
    driver: bridge
