FROM golang:1.24.2-alpine 

RUN apk update && apk add --no-cache ca-certificates

WORKDIR /server

COPY go.mod  go.mod
COPY go.sum  go.sum
RUN go mod download

COPY . .

RUN go build -o server ./cmd/main.go

CMD [ "./server" ]
